version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "44447:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookShop;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    volumes:
      - ./src/Web:/app
    working_dir: /app
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: 